# Generated by Django 2.2.3 on 2019-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tows', '0003_assignment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('ON_ROUTE', 'On Route'), ('AVAILABLE', 'Available')], default='ON_ROUTE', help_text='Crane availability', max_length=1),
        ),
    ]
