# Generated by Django 2.2.3 on 2019-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tows', '0005_auto_20190731_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crane',
            name='characteristic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crane',
            name='license_plate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crane',
            name='trademark',
            field=models.CharField(max_length=50),
        ),
    ]
