# Generated by Django 2.2.3 on 2019-08-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tows', '0006_auto_20190731_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='crane_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tows.Crane'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pilot_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tows.Pilot'),
        ),
    ]
